name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-with-kaniko-in-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build with kaniko
        run: |

          IMAGE=ghcr.io/${GITHUB_REPOSITORY}/kaniko/todo-app
          TAG=with-kaniko

          docker run \
            -v $HOME/.docker/config.json:/kaniko/.docker/config.json \
            -v $(pwd)/todo-app:/workspace \
            gcr.io/kaniko-project/executor:v1.9.0 \
            --dockerfile /workspace/Dockerfile \
            --destination "${IMAGE}:${TAG}" \
            --context dir:///workspace \
            --cache

  build-with-buildpack:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Install Pack
        run: curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.27.0/pack-v0.27.0-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack
      - name: Build with buildpack
        run: |

          IMAGE=ghcr.io/${GITHUB_REPOSITORY}/buildpack/todo-app
          TAG=with-buildpack

          pack build ${IMAGE}:${TAG}-${GITHUB_SHA} \
            --path ./todo-app \
            --cache-image ${IMAGE}:${TAG}-cache \
            --builder paketobuildpacks/builder:base \
            --publish

  build-with-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build with docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE=ghcr.io/${GITHUB_REPOSITORY}/docker/todo-app
          TAG=with-docker

          docker build --target builder \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${IMAGE}:${TAG}-builder \
            --tag ${IMAGE}:${TAG}-builder \
            todo-app

          docker build --target release \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${IMAGE}:${TAG}-builder \
            --cache-from ${IMAGE}:${TAG} \
            --tag ${IMAGE}:${TAG} \
            todo-app

          docker push ${IMAGE}:${TAG}-builder
          docker push ${IMAGE}:${TAG}

          docker tag  ${IMAGE}:${TAG} ${IMAGE}:${TAG}-${GITHUB_SHA}
          docker push ${IMAGE}:${TAG}-${GITHUB_SHA}
