name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with docker
        env:
          BUILDKIT_INLINE_CACHE: 1
        run: |
          docker build -t ghcr.io/yveskaufmann/kaniko-example:with-docker-${GITHUB_SHA} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            with-docker
          docker push ghcr.io/yveskaufmann/kaniko-example:with-docker-${GITHUB_SHA}
