name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build with docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE=ghcr.io/yveskaufmann/kaniko-example
          TAG=with-docker-${GITHUB_SHA}

          docker build -t ${IMAGE}:${TAG}-builder --target builder \
            --build-arg BUILDKIT_INLINE_CACHE=1 with-docker

          docker push ${IMAGE}:${TAG}-builder
          docker tag  ${IMAGE}:${TAG}-builder ${IMAGE}:${TAG}-builder-latest
          docker push ${IMAGE}:${TAG}-builder-latest

          docker build -t ${IMAGE}:${TAG} \
            --cache-from ${IMAGE}:${TAG}-builder \
            --cache-from ${IMAGE}:${TAG}-latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 with-docker

          docker push ${IMAGE}:${TAG}
          docker tag  ${IMAGE}:${TAG} ${IMAGE}:${TAG}-latest
          docker push ${IMAGE}:${TAG}-latest
