name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build with docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t ghcr.io/yveskaufmann/kaniko-example:with-docker-${GITHUB_SHA} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            with-docker
          docker push ghcr.io/yveskaufmann/kaniko-example:with-docker-${GITHUB_SHA}
